"""empty message

Revision ID: 195da6d2809a
Revises: 83a974f8d886
Create Date: 2025-07-29 00:37:52.845384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '195da6d2809a'
down_revision = '83a974f8d886'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('favorite_user_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorite_user_fkey', 'user', ['user'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
