"""empty message

Revision ID: 1bf8ac78be60
Revises: 195da6d2809a
Create Date: 2025-07-30 22:48:36.519230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bf8ac78be60'
down_revision = '195da6d2809a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_constraint('favorite_link_key', type_='unique')
        batch_op.drop_constraint('favorite_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.create_unique_constraint('favorite_name_key', ['name'])
        batch_op.create_unique_constraint('favorite_link_key', ['link'])

    # ### end Alembic commands ###
