"""empty message

Revision ID: 47cb4f6a1769
Revises: b23d879f251c
Create Date: 2025-07-28 23:14:17.998819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47cb4f6a1769'
down_revision = 'b23d879f251c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('link', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_constraint('character_eye_key', type_='unique')
        batch_op.drop_constraint('character_height_key', type_='unique')
        batch_op.drop_constraint('character_homeworld_key', type_='unique')
        batch_op.drop_constraint('character_mass_key', type_='unique')

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_constraint('planet_diameter_key', type_='unique')
        batch_op.drop_constraint('planet_gravity_key', type_='unique')
        batch_op.drop_constraint('planet_population_key', type_='unique')
        batch_op.drop_constraint('planet_surface_water_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.create_unique_constraint('planet_surface_water_key', ['surface_water'])
        batch_op.create_unique_constraint('planet_population_key', ['population'])
        batch_op.create_unique_constraint('planet_gravity_key', ['gravity'])
        batch_op.create_unique_constraint('planet_diameter_key', ['diameter'])

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.create_unique_constraint('character_mass_key', ['mass'])
        batch_op.create_unique_constraint('character_homeworld_key', ['homeworld'])
        batch_op.create_unique_constraint('character_height_key', ['height'])
        batch_op.create_unique_constraint('character_eye_key', ['eye'])

    op.drop_table('favorite')
    # ### end Alembic commands ###
